# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1611d31adb2afbd470123571a84422f37bd31ed90f36b60dff7cfc115ffaa75c1a210087ed4d97f357474f68379e37934e828cd8bbc51eb9e06e68515b5b6485

test:
  secret_key_base: a7ef672f473de3bbd7a041d872d0175c83d043c1ab2f7fc15f928d4b1ea07c4e55532c983d0b3164ef7f7ac0b017d17f0bfc0bb1905b1b145ba03b060da843aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
